### ISSUE TITLE
Storage backend: Migrate xrootdpyfs to PyFS 2 and XRootD5

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/xrootdpyfs#114]
WIP by Nico: https://github.com/inveniosoftware/xrootdpyfs/pull/113

- Upgrade to xrootdpyfs to PyFilesystem2
- Upgrade xrootd from v4 to v5

Due to the criticality of the storage layer, this task needs to be done by a senior person with a lot of attention to detail. Mistakes in the storage layer can severely impact operations of the repository.

Alternative options discussed but discarded:

- Stay on EOS but move from Xrootd to S3 gateway discarded because:
  - EOS team does not provide confidence in that their S3 gateway is stable.
  - Invenio-S3 would need to be reviewed and upgrade - likely considerable amount of work.
- Move to Ceph S3:
  - Invenio-S3 would need to be reviewed and upgrade - likely considerable amount of work
  - Would require moving files from EOS to Ceph - a complex task with very high impact on trust of our service if any incident happens - likely would also make the migration to InvenioRDM more complex thus increase the chance of being delayed.

Proposal is that we once migration is over review the storage and fix the issues related:
- File serving should be externalised to a file serving gateway (e.g. S3) instead of going through the app
- Backup to tape should be taken into account
- Preservation should be taken into account.

```[tasklist]
### Tasks xrootd v4
- [x] https://github.com/inveniosoftware/xrootdpyfs/issues/116
- [x] https://github.com/inveniosoftware/xrootdpyfs/issues/117
- [ ] https://github.com/inveniosoftware/xrootdpyfs/issues/121
- [x] invenio-xrootd: https://github.com/inveniosoftware/invenio-xrootd/issues/30
- [ ] invenio-xrootd: https://github.com/inveniosoftware/invenio-xrootd/issues/32
- [ ] test integration of InvenioRDM AlmaLinux, xrootd v4, and a real test EOS instance running xrootd v4
```

```[tasklist]
### Tasks xrootd v5
- [x] https://github.com/inveniosoftware/xrootdpyfs/issues/120 + release v2.0.0
- [x] invenio-xrootd: https://github.com/inveniosoftware/invenio-xrootd/issues/33
- [x] test integration of InvenioRDM AlmaLinux, xrootd v5, and a real test EOS instance running xrootd v5
```
